/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import memorygame.ArrayCardGenerator;
import memorygame.Card;
import memorygame.GenerateCardsException;

/**
 * Interfaz grafica de la aplicacion memory game
 *
 * @author daw1al13
 */
public class MainWindow extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindow.class.getName());

    private Card[][] cards;
    private Card lastCard;
    private JButton[][] botones;
    private JButton lastButton;
    private int numeroPuntosPartida;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {

        initComponents();
        botonespro08oscar
                
        
            = 
        {
            {jBF1C1,jBF2C1,jBF3C1,jBF4C1
            }
            ,
            {jBF1C2,jBF2C2,jBF3C2,jBF4C2
            }
            ,
            {jBF1C3,jBF2C3,jBF3C3,jBF4C3
            }
        };
        startNewGame(jCnivelSelector.getSelectedIndex());
    }

    public void startNewGame(int lvlPartida) throws GenerateCardsException {

        ArrayCardGenerator arrayCard = new ArrayCardGenerator();
        try {
            cards = arrayCard.generateCards(lvlPartida, 4);
        } catch (GenerateCardsException exc) {
            JOptionPane.showMessageDialog(null, exc.getMessage(), "", JOptionPane.ERROR_MESSAGE);
        }

        numeroPuntosPartida = 100;
        showGameStatus();
    }

    public void showGameStatus() {
        jLGameStatus.setText("Estas xogando o nivel " + jCnivelSelector.getItemAt(jCnivelSelector.getSelectedIndex()) + "Xogando por " + numeroPuntosPartida + " puntos");
    }

    public void clearUnselectedButtons() {
        //TODO: No me va el array de botones
    }

    public void checkGameOver() {
        int numberOfCorrectCarts = 0;
        int numberofCarts = 0;
        for (int i = 0; i < cards.length; i++) {
            for (int j = 0; j < cards[i].length; j++) {
                Card card = cards[i][j];
                numberofCarts++;
                if (card.isHit()) {
                    numberOfCorrectCarts++;
                }
            }
        }
        if (numberOfCorrectCarts == numberofCarts) {
            JOptionPane.showMessageDialog(null, "Noraboa! Acertaches todas as cartas conseguindo "+numeroPuntosPartida+" puntos", "", JOptionPane.INFORMATION_MESSAGE);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLGameStatus = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jBF4C2 = new javax.swing.JToggleButton();
        jBF2C2 = new javax.swing.JToggleButton();
        jBF2C3 = new javax.swing.JToggleButton();
        jBF4C3 = new javax.swing.JToggleButton();
        jBF1C3 = new javax.swing.JToggleButton();
        jBF4C1 = new javax.swing.JToggleButton();
        jBF3C3 = new javax.swing.JToggleButton();
        jBF2C1 = new javax.swing.JToggleButton();
        jBF1C2 = new javax.swing.JToggleButton();
        jBF1C1 = new javax.swing.JToggleButton();
        jBF3C1 = new javax.swing.JToggleButton();
        jBF3C2 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jLNivel = new javax.swing.JLabel();
        jCnivelSelector = new javax.swing.JComboBox<>();
        JBNovaPartida = new javax.swing.JToggleButton();
        JBExit = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.add(jLGameStatus);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jBF4C2.setMinimumSize(new java.awt.Dimension(200, 200));
        jBF4C2.setPreferredSize(new java.awt.Dimension(200, 200));
        jBF4C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBF4C2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPanel2.add(jBF4C2, gridBagConstraints);

        jBF2C2.setMinimumSize(new java.awt.Dimension(200, 200));
        jBF2C2.setPreferredSize(new java.awt.Dimension(200, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPanel2.add(jBF2C2, gridBagConstraints);

        jBF2C3.setMinimumSize(new java.awt.Dimension(200, 200));
        jBF2C3.setPreferredSize(new java.awt.Dimension(200, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPanel2.add(jBF2C3, gridBagConstraints);

        jBF4C3.setMinimumSize(new java.awt.Dimension(200, 200));
        jBF4C3.setPreferredSize(new java.awt.Dimension(200, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPanel2.add(jBF4C3, gridBagConstraints);

        jBF1C3.setMinimumSize(new java.awt.Dimension(200, 200));
        jBF1C3.setPreferredSize(new java.awt.Dimension(200, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jBF1C3, gridBagConstraints);

        jBF4C1.setMinimumSize(new java.awt.Dimension(200, 200));
        jBF4C1.setPreferredSize(new java.awt.Dimension(200, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPanel2.add(jBF4C1, gridBagConstraints);

        jBF3C3.setMinimumSize(new java.awt.Dimension(200, 200));
        jBF3C3.setPreferredSize(new java.awt.Dimension(200, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPanel2.add(jBF3C3, gridBagConstraints);

        jBF2C1.setMinimumSize(new java.awt.Dimension(200, 200));
        jBF2C1.setPreferredSize(new java.awt.Dimension(200, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPanel2.add(jBF2C1, gridBagConstraints);

        jBF1C2.setMinimumSize(new java.awt.Dimension(200, 200));
        jBF1C2.setPreferredSize(new java.awt.Dimension(200, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPanel2.add(jBF1C2, gridBagConstraints);

        jBF1C1.setMinimumSize(new java.awt.Dimension(200, 200));
        jBF1C1.setPreferredSize(new java.awt.Dimension(200, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPanel2.add(jBF1C1, gridBagConstraints);

        jBF3C1.setMinimumSize(new java.awt.Dimension(200, 200));
        jBF3C1.setPreferredSize(new java.awt.Dimension(200, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPanel2.add(jBF3C1, gridBagConstraints);

        jBF3C2.setMinimumSize(new java.awt.Dimension(200, 200));
        jBF3C2.setPreferredSize(new java.awt.Dimension(200, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPanel2.add(jBF3C2, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jLNivel.setText("Nivel :");
        jPanel3.add(jLNivel);

        jCnivelSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "\"Sinxelo\"", "\"Medio\" e \"Difícil\"" }));
        jCnivelSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCnivelSelectorActionPerformed(evt);
            }
        });
        jPanel3.add(jCnivelSelector);

        JBNovaPartida.setText("Nova Partida");
        jPanel3.add(JBNovaPartida);

        JBExit.setText("Sair");
        jPanel3.add(JBExit);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBF4C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBF4C2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBF4C2ActionPerformed

    private void jCnivelSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCnivelSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCnivelSelectorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton JBExit;
    private javax.swing.JToggleButton JBNovaPartida;
    private javax.swing.JToggleButton jBF1C1;
    private javax.swing.JToggleButton jBF1C2;
    private javax.swing.JToggleButton jBF1C3;
    private javax.swing.JToggleButton jBF2C1;
    private javax.swing.JToggleButton jBF2C2;
    private javax.swing.JToggleButton jBF2C3;
    private javax.swing.JToggleButton jBF3C1;
    private javax.swing.JToggleButton jBF3C2;
    private javax.swing.JToggleButton jBF3C3;
    private javax.swing.JToggleButton jBF4C1;
    private javax.swing.JToggleButton jBF4C2;
    private javax.swing.JToggleButton jBF4C3;
    private javax.swing.JComboBox<String> jCnivelSelector;
    private javax.swing.JLabel jLGameStatus;
    private javax.swing.JLabel jLNivel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    private void showGameStatus() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
