/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Modelo.Order;
import controller.RestManagerController;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author daw1al13
 */
public class OrderManageView extends javax.swing.JFrame {
    private ArrayList<Order> pedidos;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OrderManageView.class.getName());
    private RestManagerController controller;

    public void setPedidos(ArrayList<Order> listPedidos) {
        this.pedidos = listPedidos;
        DefaultListModel listModel = new DefaultListModel();
        for (Order pedidos : listPedidos){
            listModel.addElement("Mesa"+pedidos.getMesaNumber());
        }
        jListPediddos.setModel(listModel);
    }
    

    public OrderManageView(RestManagerController controller) {
         
        this.controller = controller;
        this.setVisible(true);
    }
    /**
     * Creates new form OrderManageView
     */
    public OrderManageView() {
        initComponents();
        this.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPediddos = new javax.swing.JList<>();
        jButtonActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Xestio de pedidos");

        jLabel1.setText("Lista de pedidos en curso :");

        jListPediddos.setToolTipText("");
        jListPediddos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListPediddosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListPediddos);

        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonActualizar)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jButtonActualizar)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        setPedidos(controller.refreshOrders());
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jListPediddosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListPediddosMouseClicked
        controller.showOrderDetails(pedidos.get(jListPediddos.getSelectedIndex()));
    }//GEN-LAST:event_jListPediddosMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jListPediddos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
