DELIMITER $$

DROP FUNCTION IF EXISTS DNI_cal$$

CREATE FUNCTION DNI_cal(numeros CHAR(8))
	RETURNS VARCHAR(9)
	DETERMINISTIC
BEGIN
	DECLARE resto INT;
	DECLARE letra CHAR(1);
	SET resto = numeros%23;
	SET letra = CASE resto
		WHEN 0 THEN "T"
		WHEN 1 THEN "R"
		WHEN 2 THEN "W"
		WHEN 3 THEN "A"
		WHEN 4 THEN "G"
		WHEN 5 THEN "M"
		WHEN 6 THEN "Y"
		WHEN 7 THEN "F"
		WHEN 8 THEN "P"
		WHEN 9 THEN "D"
		WHEN 10 THEN "X"
		WHEN 11 THEN "B"
		WHEN 12 THEN "N"
		WHEN 13 THEN "J"
		WHEN 14 THEN "Z"
		WHEN 15 THEN "S"
		WHEN 16 THEN "Q"
		WHEN 17 THEN "V"
		WHEN 18 THEN "H"
		WHEN 19 THEN "L"
		WHEN 20 THEN "C"
		WHEN 21 THEN "K"
		WHEN 22 THEN "E"
	END;
	RETURN CONCAT(numeros,letra);
END$$
DElIMITER ;

